from __future__ import annotations

import logging
import threading
from itertools import batched
from typing import TYPE_CHECKING, Any

from psycopg.types.json import Jsonb

from coffee_aggregator.db import migrate
from coffee_aggregator.db.connect import (
    DEFAULT_CONNECT_TIMEOUT_S,
    DEFAULT_STATEMENT_TIMEOUT_MS,
    connect,
)
from coffee_aggregator.sinks import outbox
from coffee_aggregator.sinks.base import SinkResult
from coffee_aggregator.sinks.records import coffee_record

if TYPE_CHECKING:
    from collections.abc import Iterator, Sequence

    import psycopg

    from coffee_aggregator.models import Coffee

logger = logging.getLogger(__name__)


#: Every data column of ``coffee``, in the order :func:`coffee_record` emits
#: them. The INSERT statement, the schema test and the record keys all derive
#: from this one tuple so they cannot drift apart.
COLUMNS: tuple[str, ...] = (
    "site",
    "external_id",
    "url",
    "name",
    "site_country",
    "roaster",
    "roaster_key",
    "price",
    "currency",
    "weight_g",
    "price_per_kg",
    "price_eur",
    "price_czk",
    "price_per_kg_eur",
    "price_per_kg_czk",
    "fx_rate_eur_czk",
    "fx_date",
    "available",
    "decaf",
    "origin_country",
    "origin_region",
    "origin_farm",
    "origin_producer",
    "origin_washing_station",
    "altitude_min_m",
    "altitude_max_m",
    "altitude_raw",
    "variety",
    "harvest",
    "process_method",
    "process_methods",
    "process_raw",
    "roast_level",
    "roast_raw",
    "roast_profile",
    "roast_date",
    "best_before",
    "arabica_pct",
    "robusta_pct",
    "is_blend",
    "body",
    "bitterness",
    "acidity",
    "sweetness",
    "taste_scale_max",
    "flavor_notes",
    "tasting_text",
    "brewing_methods",
    "sca_score",
    "rating",
    "rating_max",
    "review_count",
    "reviews",
    "sold_count",
    "variants",
    "images",
    "tags",
    "categories",
    "certifications",
    "awards",
    "specialty_grade",
    "original_price",
    "description",
    "origin_text",
    "raw_attributes",
    "scraped_at",
)

#: Columns stored as jsonb; their values are wrapped in :class:`Jsonb`.
JSON_COLUMNS: frozenset[str] = frozenset(
    {
        "variety",
        "flavor_notes",
        "brewing_methods",
        "process_methods",
        "reviews",
        "variants",
        "images",
        "tags",
        "categories",
        "certifications",
        "awards",
        "raw_attributes",
    }
)

#: Columns the database owns and the sink never overwrites from a record.
MANAGED_COLUMNS: tuple[str, ...] = ("first_seen_at", "last_seen_at", "delisted_at")

_KEY_COLUMNS = ("site", "external_id")
_UPDATABLE = tuple(column for column in COLUMNS if column not in _KEY_COLUMNS)

UPSERT_SQL = (
    f"INSERT INTO coffee ({', '.join(COLUMNS)}) "  # noqa: S608  (column names are a module constant)
    f"VALUES ({', '.join(['%s'] * len(COLUMNS))}) "
    "ON CONFLICT (site, external_id) DO UPDATE SET "
    + ", ".join(f"{column} = EXCLUDED.{column}" for column in _UPDATABLE)
    + ", last_seen_at = now(), delisted_at = NULL"
)

#: The data columns of ``price_history``, after the ``id``/``seen_at`` pair the
#: database fills in itself. One tuple again, so the INSERT and the schema test
#: read from the same place.
PRICE_HISTORY_COLUMNS: tuple[str, ...] = (
    "site",
    "external_id",
    "price",
    "currency",
    "weight_g",
    "available",
    "price_eur",
    "price_czk",
    "price_per_kg_eur",
    "price_per_kg_czk",
    "fx_rate_eur_czk",
)

#: One row per product per UTC day. ``seen_on`` is generated by the database
#: from ``seen_at``, and the unique index over it is what this conflicts on:
#: Lambda retries an async invocation twice by itself, and a retried crawl must
#: refresh the day it already wrote instead of appending a second one.
PRICE_HISTORY_SQL = (
    f"INSERT INTO price_history (site, external_id, seen_at, "  # noqa: S608  (a module constant)
    f"{', '.join(PRICE_HISTORY_COLUMNS[2:])}) "
    f"VALUES (%s, %s, now(), {', '.join(['%s'] * (len(PRICE_HISTORY_COLUMNS) - 2))}) "
    "ON CONFLICT (site, external_id, seen_on) DO UPDATE SET seen_at = now(), "
    + ", ".join(f"{column} = EXCLUDED.{column}" for column in PRICE_HISTORY_COLUMNS[2:])
)

#: Every column of ``coffee_variant`` the sink writes, in the order
#: :func:`variant_rows_for` emits them.
VARIANT_COLUMNS: tuple[str, ...] = (
    "site",
    "external_id",
    "variant_key",
    "variant_external_id",
    "url",
    "label",
    "weight_g",
    "price",
    "currency",
    "available",
    "price_eur",
    "price_czk",
    "price_per_kg_eur",
    "price_per_kg_czk",
    "scraped_at",
)
_VARIANT_KEY_COLUMNS = ("site", "external_id", "variant_key")
_VARIANT_UPDATABLE = tuple(
    column for column in VARIANT_COLUMNS if column not in _VARIANT_KEY_COLUMNS
)

VARIANT_UPSERT_SQL = (
    f"INSERT INTO coffee_variant ({', '.join(VARIANT_COLUMNS)}) "  # noqa: S608  (a module constant)
    f"VALUES ({', '.join(['%s'] * len(VARIANT_COLUMNS))}) "
    "ON CONFLICT (site, external_id, variant_key) DO UPDATE SET "
    + ", ".join(f"{column} = EXCLUDED.{column}" for column in _VARIANT_UPDATABLE)
    + ", last_seen_at = now()"
)

#: A shop that drops the 1 kg bag must not leave it on sale in our table, so the
#: keys this crawl saw are the only ones that survive the product's rewrite.
VARIANT_PRUNE_SQL = (
    "DELETE FROM coffee_variant "
    "WHERE site = %s AND external_id = %s AND NOT (variant_key = ANY(%s::text[]))"
)

#: It returns the rows it stamped rather than only their count, because a
#: delisting that never reaches the stream makes every consumer's copy of the
#: catalogue immortal: the coffee stops being crawled, so nothing ever
#: contradicts the last state they were sent, and a shop that closed is still
#: selling in the recommender a year later.
DELIST_SQL = (
    "UPDATE coffee SET delisted_at = now() "  # noqa: S608  (a module constant)
    "WHERE site = %s AND delisted_at IS NULL AND NOT (external_id = ANY(%s)) "
    f"RETURNING {outbox.STATE_SELECT}"
)


def row_for(coffee: Coffee) -> tuple[Any, ...]:
    """Turn one coffee into the positional parameters of :data:`UPSERT_SQL`.

    Args:
        coffee: The coffee to store.

    Returns:
        One value per entry of :data:`COLUMNS`, jsonb values already wrapped.
    """
    record = coffee_record(coffee, json_safe=False)
    return tuple(
        Jsonb(record[column]) if column in JSON_COLUMNS else record[column] for column in COLUMNS
    )


def price_row_for(coffee: Coffee) -> tuple[Any, ...]:
    """Turn one coffee into the parameters of :data:`PRICE_HISTORY_SQL`.

    Args:
        coffee: The coffee whose price is being recorded.

    Returns:
        The positional parameters.
    """
    return (
        coffee.site,
        coffee.external_id,
        coffee.price,
        coffee.currency,
        coffee.weight_g,
        coffee.available,
        coffee.price_eur,
        coffee.price_czk,
        # Stored rather than left to be divided back out later: the weight is
        # the half that goes missing when a shop changes its page, and once it
        # has, every earlier day's kilogram price becomes uncomputable too.
        coffee.price_per_kg_eur,
        coffee.price_per_kg_czk,
        coffee.fx_rate_eur_czk,
    )


def variant_rows_for(coffee: Coffee) -> list[tuple[Any, ...]]:
    """Turn one coffee's packaging options into ``coffee_variant`` rows.

    One purchasable offer is one weight at one price. A shop that also lets the
    buyer pick the grind lists that offer once per grind, which is the same bag
    as far as a price comparison is concerned, so the repeats are collapsed.
    Beyond that, two options can only be told apart by their key, so an option
    whose key repeats is dropped rather than made to fight itself inside one
    statement, which PostgreSQL refuses outright ("ON CONFLICT DO UPDATE command
    cannot affect row a second time").

    Args:
        coffee: The coffee whose variants are being stored.

    Returns:
        One tuple per distinct variant, in the order the page listed them.
    """
    rows: list[tuple[Any, ...]] = []
    seen: set[str] = set()
    offers: set[tuple[int | None, float | None, str | None]] = set()
    for index, variant in enumerate(coffee.variants):
        # A shop that sells one bag whole or ground lists the same offer several
        # times over. They are one price for one weight, and a table meant for
        # comparing prices should say so once.
        offer = (variant.weight_g, variant.price, variant.currency)
        if offer in offers:
            continue
        offers.add(offer)
        key = variant.key(index)
        if key in seen:
            logger.debug(
                "%s/%s: two variants share the key %r; keeping the first",
                coffee.site,
                coffee.external_id,
                key,
            )
            continue
        seen.add(key)
        rows.append(
            (
                coffee.site,
                coffee.external_id,
                key,
                variant.external_id,
                variant.url,
                variant.label,
                variant.weight_g,
                variant.price,
                variant.currency or coffee.currency,
                variant.available,
                variant.price_eur,
                variant.price_czk,
                variant.price_per_kg_eur,
                variant.price_per_kg_czk,
                coffee.scraped_at,
            )
        )
    return rows


def schema_columns(table: str = "coffee") -> list[str]:
    """Return the columns the packaged migrations leave a table with.

    Args:
        table: The table to collect, ``"coffee"`` or ``"price_history"``.

    Returns:
        The column names in the order the migrations introduce them.
    """
    return migrate.table_columns(table)


class SchemaOutOfDateError(RuntimeError):
    """The database is older than the code that is about to write to it."""


class PostgresSink:
    """Upserts coffees, their variants and a price-history row, one transaction per batch."""

    def __init__(
        self,
        dsn: str,
        *,
        chunk_size: int = 200,
        connect_timeout: int = DEFAULT_CONNECT_TIMEOUT_S,
        statement_timeout_ms: int = DEFAULT_STATEMENT_TIMEOUT_MS,
    ) -> None:
        """Remember the DSN; the connection is opened on first use.

        Args:
            dsn: A ``postgresql://`` connection string.
            chunk_size: How many rows go into one ``executemany`` call.
            connect_timeout: Seconds to wait for the connection itself.
            statement_timeout_ms: Milliseconds any one statement may run.
        """
        self.dsn = dsn
        self.chunk_size = max(1, chunk_size)
        self.connect_timeout = connect_timeout
        self.statement_timeout_ms = statement_timeout_ms
        self._connection: psycopg.Connection[Any] | None = None
        self._schema_checked = False
        # One psycopg connection carries one transaction, so two shops crawled
        # in parallel must not be inside it at the same time. Writes are short
        # and batched, so a single lock costs far less than a connection each.
        self._lock = threading.Lock()

    @property
    def connection(self) -> psycopg.Connection[Any]:
        """Return the live connection, opening it on first access.

        Returns:
            An open psycopg connection with autocommit disabled.
        """
        if self._connection is None or self._connection.closed:
            logger.debug("connecting to postgres")
            self._connection = connect(
                self.dsn,
                connect_timeout=self.connect_timeout,
                statement_timeout_ms=self.statement_timeout_ms,
            )
        return self._connection

    def init_schema(self) -> list[str]:
        """Apply every pending migration; safe to re-run.

        Returns:
            The versions this call applied, empty when the database was already
            up to date.
        """
        applied = migrate.apply_migrations(self.connection)
        self._schema_checked = True
        return applied

    def pending_migrations(self) -> list[str]:
        """Return the migrations this database has not seen yet.

        This is what a ``init-db --dry-run`` prints, and what
        :meth:`ensure_schema` decides on.

        Returns:
            The pending versions, in the order they would be applied.
        """
        return migrate.pending(self.connection)

    def ensure_schema(self) -> None:
        """Refuse to write to a database the packaged migrations have outrun.

        A crawl never called ``init-db``, so a deployment that shipped migration
        0003 against an 0002 database used to discover it one failing upsert at
        a time — a hundred and fifty identical tracebacks and no rows. One small
        SELECT on the first write says it once, before anything is lost.

        Raises:
            SchemaOutOfDateError: When any packaged migration is not applied.
        """
        if self._schema_checked:
            return
        outstanding = self.pending_migrations()
        if outstanding:
            message = (
                f"the database at this DSN is missing {len(outstanding)} migration(s): "
                f"{', '.join(outstanding)} — run `coffee-aggregator init-db` before crawling"
            )
            raise SchemaOutOfDateError(message)
        self._schema_checked = True

    def upsert(self, coffees: Sequence[Coffee]) -> SinkResult:
        """Write a batch of coffees, their variants and their price-history rows.

        Args:
            coffees: The batch to write.

        Returns:
            How many rows were written; a batch that fails is retried one row at
            a time, so a single malformed product costs only itself.
        """
        if not coffees:
            return SinkResult()
        with self._lock:
            self.ensure_schema()
            return self._upsert_locked(coffees)

    def _upsert_locked(self, coffees: Sequence[Coffee]) -> SinkResult:
        """Write one batch with the connection held.

        Args:
            coffees: The batch to write.

        Returns:
            How many rows were written.
        """
        connection = self.connection
        try:
            with connection.cursor() as cursor:
                for chunk in self._chunks(coffees):
                    self._write_chunk(cursor, chunk)
            connection.commit()
        except Exception:
            # Not only psycopg.Error: building a row can raise too (a date the
            # adapter mis-parsed, a value that will not serialise), and leaving
            # that transaction open would poison every later batch of the run.
            logger.exception("upsert of %d coffees failed; rolling back", len(coffees))
            self._rollback()
            return self._retry_one_by_one(coffees)
        return SinkResult(written=len(coffees), failed=0)

    def _write_chunk(self, cursor: psycopg.Cursor[Any], chunk: Sequence[Coffee]) -> None:
        """Write one chunk's data and the intent to publish it, on an open cursor.

        The outbox row rides in the same transaction as the coffee it describes.
        That is the whole point of the table: publishing from here instead would
        leave a window in which the broker has an event the database rolled
        back, or the database has a coffee the broker will never hear about.

        Args:
            cursor: The cursor of the open transaction.
            chunk: The coffees of this chunk.
        """
        cursor.executemany(UPSERT_SQL, [row_for(coffee) for coffee in chunk])
        cursor.executemany(PRICE_HISTORY_SQL, [price_row_for(coffee) for coffee in chunk])
        # The product row is written first and in the same transaction, so the
        # variants' foreign key is always satisfied by the time they arrive.
        per_coffee = [(coffee, variant_rows_for(coffee)) for coffee in chunk]
        cursor.executemany(
            VARIANT_PRUNE_SQL,
            [
                (coffee.site, coffee.external_id, [str(row[2]) for row in rows])
                for coffee, rows in per_coffee
            ],
        )
        variant_rows = [row for _, rows in per_coffee for row in rows]
        if variant_rows:
            cursor.executemany(VARIANT_UPSERT_SQL, variant_rows)
        event_rows = outbox.event_rows_for(chunk)
        if event_rows:
            cursor.executemany(outbox.OUTBOX_SQL, event_rows)

    def _retry_one_by_one(self, coffees: Sequence[Coffee]) -> SinkResult:
        """Write the rows of a failed batch separately, to lose only the bad one.

        A batch is two hundred products of one shop, and one of them holding a
        date the adapter mis-parsed used to cost the other hundred and ninety
        nine. Each row now gets its own transaction, and the row that fails is
        named in the log by the URL a human can open.

        Args:
            coffees: The batch that failed as a whole.

        Returns:
            How many of them made it on the second attempt.
        """
        if len(coffees) == 1:
            return SinkResult(written=0, failed=1)
        logger.info("retrying %d coffees one row at a time", len(coffees))
        written = 0
        failed = 0
        connection = self.connection
        for coffee in coffees:
            try:
                with connection.cursor() as cursor:
                    self._write_chunk(cursor, [coffee])
                connection.commit()
            except Exception:
                logger.exception(
                    "dropping %s/%s (%s): it cannot be written",
                    coffee.site,
                    coffee.external_id,
                    coffee.url,
                )
                self._rollback()
                failed += 1
            else:
                written += 1
        return SinkResult(written=written, failed=failed)

    def _rollback(self) -> None:
        """Undo the open transaction, tolerating a connection that is already gone."""
        try:
            self.connection.rollback()
        except Exception:  # a failed rollback must not mask the real error
            logger.exception("rollback failed")

    def _chunks(self, coffees: Sequence[Coffee]) -> Iterator[tuple[Coffee, ...]]:
        yield from batched(coffees, self.chunk_size, strict=False)

    def mark_delisted(self, site_id: str, seen_external_ids: set[str]) -> int:
        """Stamp ``delisted_at`` on every product of a site the run did not see.

        Args:
            site_id: The site whose catalogue was fully walked.
            seen_external_ids: Every id the run did see.

        Returns:
            How many rows were stamped.
        """
        if not seen_external_ids:
            # An empty set means "the run saw nothing", which is a broken crawl,
            # not an empty catalogue; delisting on it would wipe the whole shop.
            logger.warning("%s: refusing to delist, the run saw no products at all", site_id)
            return 0
        with self._lock:
            self.ensure_schema()
            return self._delist_locked(site_id, seen_external_ids)

    def _delist_locked(self, site_id: str, seen_external_ids: set[str]) -> int:
        """Stamp the rows, and announce each one, with the connection held.

        The events are written from the rows the UPDATE returned and inside its
        transaction, so a delisting is announced exactly when it is recorded.

        Args:
            site_id: The site whose catalogue was fully walked.
            seen_external_ids: Every id the run did see.

        Returns:
            How many rows were stamped.
        """
        connection = self.connection
        try:
            with connection.cursor() as cursor:
                cursor.execute(DELIST_SQL, (site_id, list(seen_external_ids)))
                stamped = cursor.fetchall()
                events = outbox.event_rows_from_db(stamped)
                if events:
                    cursor.executemany(outbox.OUTBOX_SQL, events)
            connection.commit()
        except Exception:  # one shop's failure never aborts a --site all run
            logger.exception("delisting for %s failed", site_id)
            self._rollback()
            return 0
        return len(stamped)

    def close(self) -> None:
        """Commit anything outstanding and close the connection."""
        with self._lock:
            self._close_locked()

    def _close_locked(self) -> None:
        """Close the connection with the lock held."""
        if self._connection is None or self._connection.closed:
            return
        try:
            self._connection.commit()
        finally:
            self._connection.close()
            self._connection = None
